version: '2'
services:
    vsftpd-server:
      build: ./spec/docker/vsftpd
      container_name: vsftpd-server
      environment:
        - FTP_USER=ftpuser
        - FTP_PASS=supersecret
        - ONLY_UPLOAD=NO
        - PASV_ENABLE=YES
        - PASV_ADDRESS=192.168.0.6
        - PASV_MIN=21200
        - PASV_MAX=21210
      ports:
        - "21:21"
        - "21200-21210:21200-21210"
      networks:
        my_net:
          ipv4_address: 192.168.0.6
    rspec-ruby25:
      image: ruby:latest
      build: ./spec/docker/rspec
      container_name: rspec-ruby25
      volumes:
        - .:/work
      command: tail -f /dev/null
      networks:
        my_net:
          ipv4_address: 192.168.0.5
    rspec-ruby24:
      image: ruby:2.4
      build: ./spec/docker/rspec
      container_name: rspec-ruby24
      volumes:
        - .:/work
      command: tail -f /dev/null
      networks:
        my_net:
          ipv4_address: 192.168.0.4
    rspec-ruby23:
      image: ruby:2.3
      build: ./spec/docker/rspec
      container_name: rspec-ruby23
      volumes:
        - .:/work
      command: tail -f /dev/null
      networks:
        my_net:
          ipv4_address: 192.168.0.3
    # ftp-client:
    #   image: ftp
    #   container_name: ftp-client
    #   working_dir: /work
    #   volumes:
    #     - .:/work
    #   command: tail -f /dev/null
    #   networks:
    #     my_net:
    #       ipv4_address: 192.168.0.2
networks:
  my_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 192.168.0.0/16
         gateway: 192.168.0.1
